name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: make test, make build, make docker-image
      run: |
        make test
        # make
        # make container-image
    - name: Identify the event info
      run: |
        echo github.event_name - ${{ github.event_name }}
        echo github.ref -branch or tag - ${{ github.ref }} 
        echo github.head_ref - source branch - ${{ github.head_ref }} 

