name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check system
      run: go version
    - name: Pre build tests
      run: make test
    - name: Build binary
      run: make
    - name: Build docker image
      run: make container-image

